import {
  SCN_APPROVAL_STATUSES,
  SCN_CATEGORIES,
  SCN_PRELIMINARY_REVIEW_OPTIONS,
  SCN_PROJECT_STATUS_OPTIONS,
  SCN_SECONDARY_REVIEW_OPTIONS,
  SCN_STATUSES,
} from "@/types/task";

// =============================================================================
// SCN Dashboard — the columns, as DATA.
//
// Declared once here and the mapper, the write payload, the $select, the
// detail cards and the FieldEditModal specs are all driven from it — the same
// arrangement as grayMarketFields.ts, and for the same reason: several of the
// internal names do NOT say what they mean, and a label typed into a view is
// how two screens end up calling one column different things.
//
// Column names come from the live list (scripts/scn-dashboard-schema.json,
// captured 2026-10-07). The ones that lie:
//
//   Progress        → the PRODUCT name, not a progress value
//   Priority        → the CATEGORY (OBS / PHASE OUT / EECR / Notification)
//   PartsEffected   → labelled "Old Number"
//   EOLExpires      → labelled "LTS Expires"
//   Title           → the SCN# (YYYY-NNNN), generated by lib/scnNumber.ts
//
// Guessing any of those from the label writes to a column that doesn't
// exist — which SharePoint accepts silently on some paths and 400s on others.
// =============================================================================

/**
 * Where a field is shown. The four CARD sections are the detail page's
 * cards, in order; "Sidebar" holds the header/sidebar controls (status,
 * approval, the two person columns), which have their own rendering.
 */
export type ScnSection = "Notice" | "Parts" | "Review" | "Outcome" | "Sidebar";

/** The detail page's cards, in order. The sidebar is not a card. */
export const SCN_SECTIONS: ScnSection[] = ["Notice", "Parts", "Review", "Outcome"];

/**
 *  text / multiline / choice  → a string, in `Scn.values` (or a NAMED field —
 *                               see `named`)
 *  multiChoice                → a string[], in `Scn.checks`
 *  date                       → a Date | null, in `Scn.dates`
 *  person                     → a Person[], a named field (assignedTo / owner)
 *  link                       → a Hyperlink column, read-only (`Scn.taskList`)
 */
export type ScnFieldKind =
  | "text"
  | "multiline"
  | "choice"
  | "multiChoice"
  | "date"
  | "person"
  | "link";

export interface ScnField {
  /** Domain key — `Scn.values[key]` / `Scn.checks[key]` / `Scn.dates[key]`, or the named field. */
  key: string;
  /** SharePoint internal column name — the thing that must be exact. */
  column: string;
  /** The label to SHOW. Where it differs from the column's own display name, this one wins. */
  label: string;
  kind: ScnFieldKind;
  section: ScnSection;
  /** Choice / multi-choice options, verbatim from the column definition. */
  options?: readonly string[];
  /** Read and shown, never written (`Task_x0020_List`). */
  readOnly?: boolean;
  /** SharePoint refuses a blank on create (`ApprovalStatus`). */
  required?: boolean;
  /** The column's own cap (`ECN` is 10 characters). */
  maxLength?: number;
  /**
   * A string column that lives as a NAMED property on `Scn` (product,
   * category, status, approvalStatus) rather than in `values` — they are the
   * list's columns, the sidebar's controls and the header's chips, so a
   * named property is what every screen sorts and filters on.
   */
  named?: boolean;
  /**
   * A TEXT column filled from Engineering's Project References and stored as
   * the project's title (`lib/scnProjects.ts`). It can't be a real lookup —
   * the Projects list is in another site collection.
   */
  project?: boolean;
}

/**
 * Every column except Title, YEAR, Watchers, Communication and Attachments
 * (those need their own handling: numbering, the comment thread, the
 * attachment store). In the order each card renders them.
 */
export const SCN_FIELDS: ScnField[] = [
  // ---- Sidebar ------------------------------------------------------------
  { key: "status", column: "SCNStatus", label: "SCN Status", kind: "choice", section: "Sidebar", options: SCN_STATUSES, named: true },
  { key: "approvalStatus", column: "ApprovalStatus", label: "Approval Status", kind: "choice", section: "Sidebar", options: SCN_APPROVAL_STATUSES, required: true, named: true },
  { key: "assignedTo", column: "AssignedTo", label: "Assigned to", kind: "person", section: "Sidebar" },
  { key: "owner", column: "Owner", label: "Owner", kind: "person", section: "Sidebar" },

  // ---- Notice -------------------------------------------------------------
  { key: "product", column: "Progress", label: "Product", kind: "text", section: "Notice", named: true }, // NOT a progress value
  { key: "category", column: "Priority", label: "Category", kind: "choice", section: "Notice", options: SCN_CATEGORIES, named: true }, // NOT a priority
  { key: "description", column: "Description", label: "Description", kind: "multiline", section: "Notice" },
  { key: "customer", column: "Customer", label: "Customer", kind: "text", section: "Notice" },
  { key: "customerRef", column: "CustomerRef_x0023_", label: "Customer Ref#", kind: "text", section: "Notice" },
  { key: "customerProduct", column: "CustomerProduct", label: "Customer Product", kind: "text", section: "Notice" },

  // ---- Parts --------------------------------------------------------------
  { key: "oldNumber", column: "PartsEffected", label: "Old Number", kind: "multiline", section: "Parts" }, // several per line
  { key: "sapNumber", column: "SAPNumber", label: "SAP Number", kind: "multiline", section: "Parts" },
  { key: "drawingNumber", column: "DrawingNumber", label: "Drawing Number", kind: "multiline", section: "Parts" },
  { key: "partDescription", column: "PartDescription", label: "Part Description", kind: "multiline", section: "Parts" },
  { key: "ecn", column: "ECN", label: "ECN", kind: "text", section: "Parts", maxLength: 10 },

  // ---- Review -------------------------------------------------------------
  { key: "preliminaryReviews", column: "PreliminaryReviews", label: "Preliminary Reviews", kind: "multiChoice", section: "Review", options: SCN_PRELIMINARY_REVIEW_OPTIONS },
  { key: "secondaryReview", column: "SecondaryReview", label: "Secondary Review", kind: "multiChoice", section: "Review", options: SCN_SECONDARY_REVIEW_OPTIONS },
  { key: "projectStatus", column: "ProjectStatus", label: "Project Status", kind: "multiChoice", section: "Review", options: SCN_PROJECT_STATUS_OPTIONS },
  { key: "signOffStatus", column: "Sign_x002d_off_x0020_status", label: "Sign-off status", kind: "text", section: "Review" }, // free text holding NAMES — no choice list
  { key: "fixtureReview", column: "FixtureReview", label: "Fixture Review", kind: "date", section: "Review" },

  // ---- Outcome ------------------------------------------------------------
  { key: "finalDisposition", column: "FinalDisposition", label: "Final Disposition", kind: "text", section: "Outcome" },
  { key: "salesHistory", column: "SalesHistory", label: "Sales History", kind: "multiline", section: "Outcome" },
  { key: "ltsExpires", column: "EOLExpires", label: "LTS Expires", kind: "date", section: "Outcome" }, // column says EOL, label says LTS
  { key: "ltbExpires", column: "LTBExpires", label: "LTB Expires", kind: "date", section: "Outcome" },
  { key: "projectReference", column: "ProjectReference", label: "Project Reference", kind: "text", section: "Sidebar", project: true }, // TEXT, picked from Engineering's Projects
  { key: "taskList", column: "Task_x0020_List", label: "Task List", kind: "link", section: "Sidebar", readOnly: true }, // written by setScnTask, not the descriptor path
  { key: "notes", column: "Notes", label: "Notes", kind: "multiline", section: "Outcome" }, // a running dated log
];

export function scnFieldsInSection(section: ScnSection): ScnField[] {
  return SCN_FIELDS.filter((f) => f.section === section);
}

export function scnField(key: string): ScnField | undefined {
  return SCN_FIELDS.find((f) => f.key === key);
}

/** The field's label, by key — the one place a label comes from. */
export function scnFieldLabel(key: string): string {
  return scnField(key)?.label ?? key;
}

/** column → domain key, for the mock branch and the reverse mapping. */
export const SCN_COLUMN_KEYS: Record<string, string> = Object.fromEntries(
  SCN_FIELDS.map((f) => [f.column, f.key]),
);

/**
 * The three genuine MULTI-choice columns (`displayAs: "checkBoxes"`, arrays on
 * the live rows). These — and ONLY these — take the `Collection(Edm.String)`
 * annotation on a write; see annotateMultiChoiceFields in lib/graphFields.ts.
 * `SCNStatus`, `Priority` and `ApprovalStatus` are single dropDowns and must
 * never be annotated.
 */
export const SCN_MULTI_CHOICE_COLUMNS: readonly string[] = SCN_FIELDS.filter(
  (f) => f.kind === "multiChoice",
).map((f) => f.column);

/** The three date-only columns. */
export const SCN_DATE_COLUMNS: readonly string[] = SCN_FIELDS.filter(
  (f) => f.kind === "date",
).map((f) => f.column);

/**
 * The `$select` for a read — every descriptor column plus the named ones.
 * The three person columns are MULTI-value, so Graph expands them in full
 * and no `<Name>LookupId` sibling is needed here (that trap is the
 * SINGLE-value one — see "A single-person column needs BOTH halves selected"
 * in CLAUDE.md).
 */
export const SCN_SELECT = [
  "Title",
  "YEAR",
  "Watchers",
  "Communication",
  "Attachments",
  "Created",
  "Modified",
  ...SCN_FIELDS.map((f) => f.column),
].join(",");
